name: xdem
channels:
  - conda-forge
dependencies:
  - python=3
  - proj=7.2
  - geopandas
  - ipython
  - matplotlib
  - pdal
  - python-pdal
  - pytest
  - pyproj
  - rasterio
  - scipy
  - tqdm
  - pip
  - proj-data
  - pip:
    - richdem
#    - "--editable=git+https://github.com/GlacioHack/GeoUtils.git#egg=GeoUtils"
#    - "--editable=git+https://github.com/GlacioHack/xdem.git#egg=xdem"
